package main

import (
	"fmt"
	"github.com/bixlabs/go-layout/api/todo"
	_ "github.com/bixlabs/go-layout/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/bixlabs/go-layout/todo/interactors"
	"github.com/bixlabs/go-layout/tools"
	"github.com/caarlos0/env"
	"github.com/gin-gonic/gin"
	_ "github.com/joho/godotenv/autoload"
	ginSwagger "github.com/swaggo/gin-swagger"
	"github.com/swaggo/gin-swagger/swaggerFiles"
)

// @title Go-Layout
// @version 1.0
// @description Simple template to use for golang projects

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email jarrieta@bixlabs.com

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html
// @BasePath /v1

func main() {
	tools.InitializeLogger()
	router := NewGinRouter()
	todoOperations := interactors.NewTodoOperationsHandler()
	todo.NewTodoRestConfigurator(todoOperations, router)
	runGinRouter(router, getRestConfiguration().Port)
}

func NewGinRouter() *gin.Engine {
	result := gin.Default()
	result.Use(gin.Logger())
	result.Use(gin.Recovery())
	configureSwagger(result)
	return result
}

func configureSwagger(result *gin.Engine) gin.IRoutes {
	return result.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
}

func runGinRouter(router *gin.Engine, port string) {
	err := router.Run(fmt.Sprintf(":%s", port))
	if err != nil {
		panic(err)
	}
}

func getRestConfiguration() RestConfiguration {
	result := RestConfiguration{}
	err := env.Parse(&result)
	if err != nil {
		tools.Log().Panic("parsing the env variables for the rest configuration threw an error", err)
	}
	return result
}

type RestConfiguration struct {
	Port string `env:"AUTH_SERVER_PORT" envDefault:"8080"`
}
